### PR TITLE
Add support for Qt6

### PR DESCRIPTION
**Pull request by tuxmaster5000**
Let it build using Qt6

### CODE REVIEW

**Comment by lvwujun** [comment]
We need the ci process result to verify the PR is OK or not that can commit this change.

**Comment by BLumia** [comment]
> We need the ci process result to verify the PR is OK or not that can commit this change.

The CI won't get trigger because the CI is added after this PR get created

Hi @tuxmaster5000, could you please amend your commit and ensure your commit message aligned to the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) guideline? After you amend the commit and do a re-push, the CI should also get triggered so we can check if anything went wrong or if we can merge it. Thanks!

**Comment by LordGrimmauld** [comment]
Hey, is this still being worked on? i am working on a qt6 based project where i need to interact with gio, this seems interesting but hard to use if qt5-only. I might target the fork instead for testing purposes but something official would be nice.

**Comment by BLumia** [comment]
> Hey, is this still being worked on? i am working on a qt6 based project where i need to interact with gio, this seems interesting but hard to use if qt5-only. I might target the fork instead for testing purposes but something official would be nice.

`gio-qt` is no longer heavily used by deepin now (the file manager team now use [utils-dfm](https://github.com/linuxdeepin/util-dfm), but it's also qt5-only for now), but the codebase itself is quite straight forward so you can simply pick-up and use it in Qt 6. Even if this PR is merged, we might not work on releasing a new tag version or building a qt6 package for this repo unless this project is still required by some other repo.

So, if your project will be used in a long run, I see the following option:

1. Targeting a fork of gio-qt, or fork and maintain it by yourself. This could provide you more freedom to add new APIs which are not included in the current version of gio-qt
2. Try using [`giomm` and `glibmm`](https://developer-old.gnome.org/glibmm/stable/) directly, which is still a set of C++ style API.
3. Write your own binding by making use of  `gobject-consume`. This is certainly a better choice so you won't need to depend on `giomm` any more and you can then generate binding for most of the existing gio APIs, but working on this might take some time to do so might not be a good idea if you don't have enough time.

**Comment by LordGrimmauld** [comment]
Targetting a fork is super easy using nix tooling (which i already use and love). Unil i am set on an api to use, this will at least be my way to test. Raw dependencies on giomm/glibmm are a reasonable alternative, but take significantly more effort than i expected would be a relatively small feature set. I'll have a second look though.

**Comment by BLumia** [comment]
Closed in favor of https://github.com/linuxdeepin/gio-qt/pull/18#issuecomment-1104614358 and https://github.com/linuxdeepin/gio-qt/pull/37, now the master branch should also have proper CI build for both Qt5 and Qt 6.

Still, thanks again for your contribution :)

**Pull request closed without merging**
